### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [flomikoon/Checker#1]
Пока не проработан контроль правил. Вот, что мне удалось заметить
1. Очерёдность ходов не котроллируется
2. Обязательное взятие не контролируется
3. Дамка может перепрыгивать через свою дамку

**Comment by flomikoon** [comment]
*Дамка перепрыгивает через свою дамку - Исправлено
*Очередность ходов не контролировалась - Исправлено
*Обязательное взятие не контролировалось - Исправлено

**Comment by Aidagots** [comment]
*Обязательное взятие не контролируется - Исправлено

**Comment by gagarski** [comment]
Баг:
Белые: A3 -> B4
Серые: B6 -> C5
Ход белых - невозможно сделать, серые тоже ходить не могут.

**Comment by gagarski** [comment]
Остальные правила проверить не удалось, этот баг мешает создать ситуацию с дамками, например.

**Comment by flomikoon** [comment]
Исправленно

**Comment by gagarski** [comment]
<img src="https://i.imgur.com/7ORAfoZ.png"/>

Никто не может ходить. К сожалению, не помню последовательность, которая привела к этому. Вроде недавно было длинное взятие с переходом в дамки в процессе.

По коду: слишком много адской копипасты, хорошо бы избавиться от неё (а то до бесконечности будете там баговать).
